subprojects {
    group = 'org.itmo'
    version = '0.1.0-SNAPSHOT'

    repositories {
        mavenCentral()
    }

    plugins.withType(JavaPlugin).configureEach {
        extensions.getByType(JavaPluginExtension).toolchain.languageVersion = JavaLanguageVersion.of(17)
        tasks.withType(JavaCompile).configureEach {
            options.encoding = 'UTF-8'
            options.compilerArgs << '-parameters'
        }
    }
}
